# Regresión Lineal Multiple

In [26]:
import numpy as np


def get_params(data):
    row_1 = np.mean(data, axis=0)
    row_2 = np.ptp(data, axis=0)

    return row_1, row_2


def scale(data, averages, ranges):
    return np.divide(data - averages, ranges)


data = np.array([[3, 4, 195, 460],
                 [2, 2, 131, 232],
                 [2, 3, 142, 135],
                 [1, 1, 80, 178]])
print(f'Datos:\n{data[:, 0:3]}\n')

averages, ranges = get_params(data[:, 0:3])
print(f'Promedios:\n{averages}\n')
print(f'Rangos:\n{ranges}\n')

scaled_data = scale(data[:, 0:3], averages, ranges)
print(f'Datos escalados:\n{scaled_data}\n')

Datos:
[[  3   4 195]
 [  2   2 131]
 [  2   3 142]
 [  1   1  80]]

Promedios:
[  2.    2.5 137. ]

Rangos:
[  2   3 115]

Datos escalados:
[[ 0.5         0.5         0.50434783]
 [ 0.         -0.16666667 -0.05217391]
 [ 0.          0.16666667  0.04347826]
 [-0.5        -0.5        -0.49565217]]

