In [51]:
import numpy as np
import matplotlib as plt

a = np.array([
    [1, 2310, 2, 2, 20],
    [1, 2333, 2, 2, 1.2],
    [1, 2356, 3, 1.5, 33],
    [1, 2379, 3, 2, 43],
    [1, 2402, 2, 3, 53],
    [1, 2425, 4, 2, 23],
    [1, 2448, 2, 1.5, 99],
    [1, 2471, 2, 2, 34],
    [1, 2494, 3, 3, 23],
    [1, 2517, 4, 4, 55],
    [1, 2540, 2, 3, 22]
])

y = np.array([
    [142000],
    [144000],
    [151000],
    [150000],
    [139000],
    [169000],
    [126000],
    [142900],
    [163000],
    [169000],
    [149000]
])

x = np.linalg.inv(a.T.dot(a)).dot(a.T).dot(y)
x0, x1, x2, x3, x4 = x.flatten()

valor_calculado = []

for i in range(a.shape[0]):
    a0, a1, a2, a3, a4 = a[i]
    resultado = x0 + x1 * a1 + x2 * a2 + x3 * a3 + x4 * a4
    valor_calculado.append(resultado)

error = []

for i in range (y.shape[0]):
    result = valor_calculado[i] - y[i]
    error.append(result)

error_cuadratico = []
error_cuadratico_total = 0

for i in range(len(error)):
    result = error[i] * error[i]
    error_cuadratico.append(result)
    error_cuadratico_total += result

print('a = ', a, sep='\n', end='\n\n')
print('y = ', y, sep='\n', end='\n\n')
print('x = ', x, sep='\n', end='\n\n')
print('valor calculado = ', valor_calculado, sep='\n', end='\n\n')
print('error = ', error, sep='\n', end='\n\n')
print('error cuadratico = ', error_cuadratico, sep='\n', end='\n\n')
print(f'(Y\' - Y)^2 = {error_cuadratico_total}')
print(f'm = {a.shape[0]}')
print('j = ', np.sum(np.power(a@x-y, 2))/(2*y.size), end='\n\n')

a = 
[[1.000e+00 2.310e+03 2.000e+00 2.000e+00 2.000e+01]
 [1.000e+00 2.333e+03 2.000e+00 2.000e+00 1.200e+00]
 [1.000e+00 2.356e+03 3.000e+00 1.500e+00 3.300e+01]
 [1.000e+00 2.379e+03 3.000e+00 2.000e+00 4.300e+01]
 [1.000e+00 2.402e+03 2.000e+00 3.000e+00 5.300e+01]
 [1.000e+00 2.425e+03 4.000e+00 2.000e+00 2.300e+01]
 [1.000e+00 2.448e+03 2.000e+00 1.500e+00 9.900e+01]
 [1.000e+00 2.471e+03 2.000e+00 2.000e+00 3.400e+01]
 [1.000e+00 2.494e+03 3.000e+00 3.000e+00 2.300e+01]
 [1.000e+00 2.517e+03 4.000e+00 4.000e+00 5.500e+01]
 [1.000e+00 2.540e+03 2.000e+00 3.000e+00 2.200e+01]]

y = 
[[142000]
 [144000]
 [151000]
 [150000]
 [139000]
 [169000]
 [126000]
 [142900]
 [163000]
 [169000]
 [149000]]

x = 
[[ 4.38816972e+04]
 [ 3.07074129e+01]
 [ 1.27450358e+04]
 [ 2.45998327e+03]
 [-2.22758521e+02]]

valor calculado = 
[np.float64(140770.68867097783), np.float64(145664.81935317567), np.float64(150802.4130920932), np.float64(150511.09001599732), np.float64(138704.72274269312), np.float64(1