In [7]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [6]:
import time
import numpy as np
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# print(a[0:20])

# Version clasica con ciclo for
tic = time.time()
n = len(a)
c = 0
for i in range(n):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("Versión clásica " + str(1000*(toc-tic)) + "ms")

# Version vectorizada
tic = time.time()
c = np.dot(a, b)
toc = time.time()
print(c)
print("Versión vectorizada " + str(1000*(toc-tic)) + "ms")

249978.25208498427
Versión clásica 434.45444107055664ms
249978.2520849827
Versión vectorizada 4.51350212097168ms


Supón que tienes un vector V, y que vas a crear un vector U donde los elementos $U_j= e^{V_j}$ 

In [8]:
import numpy as np
import time

V = np.random.rand(1000000)

# Version clasica con ciclo for
tic = time.time()
n = len(V)
U = np.zeros([n, 1])
for i in range(n):
    U[i] = np.exp(V[i])
toc = time.time()
print(U)
print("Versión clásica " + str(1000*(toc-tic)) + "ms")

# Version vectorizada
tic = time.time()
U = np.exp(V)
toc = time.time()
print(U)
print("Versión vectorizada " + str(1000*(toc-tic)) + "ms")

[[1.62897624]
 [1.52731369]
 [1.30781706]
 ...
 [2.47444519]
 [1.39891488]
 [1.04436398]]
Versión clásica 1894.4697380065918ms
[1.62897624 1.52731369 1.30781706 ... 2.47444519 1.39891488 1.04436398]
Versión vectorizada 3.610372543334961ms
